/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_HNLP_24.c                                        *
* Font:        HelveticaNeueLT Pro 43 LtEx                           *
* Height:      23                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  23                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\XkapSourceCode\Xkap-Stm32\Xkap-Stm32(xsl201603220900)\Resource\Font_HNLP_24.txt*
*                                                                    *
**********************************************************************
*                                                                    *
* Read pattern file: E:\XkapSourceCode\Xkap-Stm32\Xkap-Stm32(xsl201603220900)\Resource\Font_HNLP_24.txt*
* Edit/Insert/Right     at character 0x2D (45)                       *
* Edit/Insert/Left      at character 0x2D (45)                       *
* Edit/Insert/Right     at character 0x2D (45)                       *
* Edit/Insert/Left      at character 0x2D (45)                       *
* Edit/Insert/Right     at character 0x3A (58)                       *
* Edit/Insert/Left      at character 0x3A (58)                       *
* Edit/Insert/Right     at character 0x3A (58)                       *
* Edit/Insert/Left      at character 0x3A (58)                       *
* Edit/Insert/Right     at character 0x3A (58)                       *
* Edit/Insert/Left      at character 0x3A (58)                       *
* Edit/Insert/Right     at character 0x3A (58)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Left      at character 0x31 (49)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Left      at character 0x31 (49)                       *
* Edit/Insert/Left      at character 0x37 (55)                       *
*                                                                    *
**********************************************************************
  C-file modified by Font converter for emWin version 5.22: Mar 23 2016 at 11:02:12
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_HNLP_24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_002D[ 46] = { /* code 002D, HYPHEN-MINUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0030[ 46] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XX___,_XX_____,
  __XX____,__XX____,
  __XX____,__XX____,
  __X_____,___X____,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __X_____,___X____,
  __XX____,__XX____,
  __XX____,__XX____,
  ___XX___,_XX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0031[ 46] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _______X,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  _______X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0032[ 46] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XXX___,_XX_____,
  __XX____,__X_____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  ________,__XX____,
  ________,_XX_____,
  ________,_XX_____,
  _______X,X_______,
  ______XX,________,
  ____XXX_,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0033[ 46] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  ___XX___,_XX_____,
  __XX____,__X_____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  ________,__X_____,
  ________,_XX_____,
  ______XX,XXX_____,
  ________,__XX____,
  ________,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __XX____,___X____,
  __XXX___,__XX____,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0034[ 46] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,XX______,
  _______X,XX______,
  ______XX,XX______,
  ______X_,XX______,
  _____X__,XX______,
  ____XX__,XX______,
  ___XX___,XX______,
  __XX____,XX______,
  __X_____,XX______,
  _X______,XX______,
  XXXXXXXX,XXXXX___,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0035[ 46] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  __XX____,________,
  __XX____,________,
  __X__XXX,XX______,
  __XXX___,_XXX____,
  __X_____,__XX____,
  ________,___XX___,
  ________,___XX___,
  _XX_____,___XX___,
  __X_____,___X____,
  ___XX___,_XXX____,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0036[ 46] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ____X___,XXX_____,
  ___X____,__X_____,
  __XX____,__XX____,
  __X_____,________,
  _XX_____,________,
  _XX__XXX,XX______,
  _XX_X___,_XXX____,
  _XXX____,__XX____,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __X_____,___XX___,
  __XX____,__XX____,
  ___XX___,_XX_____,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0037[ 46] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXX____,
  ________,__XX____,
  ________,__X_____,
  ________,_X______,
  ________,XX______,
  ________,X_______,
  _______X,X_______,
  _______X,________,
  ______XX,________,
  ______X_,________,
  _____XX_,________,
  _____XX_,________,
  _____X__,________,
  ____XX__,________,
  ____XX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0038[ 46] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XX____,_XX_____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  _XX_____,__XX____,
  __XX____,_XX_____,
  ____XXXX,X_______,
  __XXX___,_XXX____,
  __X_____,___X____,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __XX____,__XX____,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_0039[ 46] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  ___XX___,_XX_____,
  __XX____,__XX____,
  _XX_____,___X____,
  _XX_____,___XX___,
  _XX_____,___XX___,
  _XX_____,___XX___,
  __XX____,__XXX___,
  ___XX___,_X_XX___,
  ____XXXX,X__XX___,
  ________,___X____,
  _XX_____,__XX____,
  __X_____,__X_____,
  __XXX___,_X______,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_24_003A[ 46] = { /* code 003A, COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFont_HNLP_24_CharInfo[12] = {
   {  13,  13,  2, acGUI_FontFont_HNLP_24_002D } /* code 002D */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0030 } /* code 0030 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0031 } /* code 0031 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0032 } /* code 0032 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0033 } /* code 0033 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0034 } /* code 0034 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0035 } /* code 0035 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0036 } /* code 0036 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0037 } /* code 0037 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0038 } /* code 0038 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_0039 } /* code 0039 */
  ,{  13,  13,  2, acGUI_FontFont_HNLP_24_003A } /* code 003A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_HNLP_24_Prop2 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontFont_HNLP_24_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_HNLP_24_Prop1 = {
   0x002D /* first character */
  ,0x002D /* last character  */
  ,&GUI_FontFont_HNLP_24_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_HNLP_24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_HNLP_24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,23 /* height of font  */
  ,23 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_HNLP_24_Prop1}
  ,0 /* Baseline */
  ,0 /* Height of lowercase characters */
  ,0 /* Height of capital characters */
};

