/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_ST_24.c                                          *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\XkapSourceCode\Xkap-Stm32\Xkap-Stm32(xsl201606011700)\Resource\Font_ST_24.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ST_24;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_0020[ 48] = { /* code 0020, SPACE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_5206[ 72] = { /* code 5206 */
  ________,________,________,
  ________,________,________,
  ________,______X_,________,
  ________,XXX___X_,________,
  ________,XX____X_,________,
  _______X,X______X,________,
  _______X,_______X,________,
  ______XX,________,X_______,
  ______X_,________,XX______,
  _____X__,________,_XX_____,
  ____X___,________,X_XXX___,
  ___X_XXX,XXXXXXXX,XX_XXXX_,
  __X_____,__X_____,X_______,
  ________,_XX_____,X_______,
  ________,_XX_____,X_______,
  ________,_X______,X_______,
  ________,_X______,X_______,
  ________,X_______,X_______,
  ________,X_______,X_______,
  _______X,_______X,X_______,
  ______X_,_______X,X_______,
  _____X__,____XXXX,________,
  ___XX___,_____XX_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_544A[ 72] = { /* code 544A */
  ________,________,________,
  ________,________,________,
  ______X_,___XXX__,________,
  ______XX,___XX___,________,
  ______X_,___XX___,________,
  _____XX_,___XX___,_XX_____,
  _____X_X,XXXXXXXX,X_______,
  ____X___,___XX___,________,
  ___X____,___XX___,________,
  __X_____,___XX___,________,
  ________,___XX___,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_62A5[ 72] = { /* code 62A5 */
  ________,________,________,
  ________,________,________,
  _____XX_,___X____,__X_____,
  _____XX_,___XXXXX,XXXX____,
  _____XX_,___X____,__X_____,
  _____XX_,___X____,__X_____,
  _____XX_,X__X____,__X_____,
  _XXXXXXX,XX_X____,__X_____,
  _____XX_,__XX___X,XXX_____,
  _____XX_,___X____,_X______,
  _____XX_,___X____,___X____,
  _____XX_,X__XXXXX,XXXXX___,
  _____XXX,___X_X__,___X____,
  __XXXXX_,___X__X_,__X_____,
  _XX__XX_,___X__X_,__X_____,
  _____XX_,___X___X,_XX_____,
  _____XX_,___X____,XX______,
  _____XX_,___X____,XX______,
  _____XX_,___X___X,_XX_____,
  _____XX_,___X__X_,__XX____,
  _____XX_,___X_X__,___XXXX_,
  __XXXXX_,___XX___,________,
  ____XX__,___X____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_63D0[ 72] = { /* code 63D0 */
  ________,________,________,
  ________,________,________,
  _____XX_,___X____,__X_____,
  _____X__,___XXXXX,XXXX____,
  _____X__,___X____,__XX____,
  _____X__,___X____,__XX____,
  _____X_X,X__XXXXX,XXXX____,
  __XXXXX_,___X____,__XX____,
  _____X__,___X____,__XX____,
  _____X__,___X____,__XX____,
  _____X__,X__XXXXX,XXXX____,
  _____XXX,________,________,
  ____XX__,________,____XX__,
  __XX_X__,_XXXXXXX,XXXX____,
  __X__X__,__X____X,________,
  _____X__,__X____X,________,
  _____X__,__X____X,XXXXX___,
  _____X__,__X____X,________,
  _____X__,_X_X___X,________,
  _____X__,_X__X__X,________,
  _____X__,X____XXX,________,
  ___XXX_X,______XX,XXXXXX__,
  ____X_X_,________,__XXX___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_7720[ 72] = { /* code 7720 */
  ________,________,________,
  ________,________,________,
  ________,__X_____,___XX___,
  __X___XX,__XXXXXX,XXXXX___,
  __XXXXXX,__X_____,___XX___,
  __X___XX,__X_____,___XX___,
  __X___XX,__X_____,___XX___,
  __X___XX,__X_____,___XX___,
  __X___XX,__XXXXXX,XXXXX___,
  __XXXXXX,__X____X,________,
  __X___XX,__X____X,________,
  __X___XX,__X____X,____X___,
  __X___XX,__XXXXXX,XXXXXX__,
  __X___XX,__X____X,________,
  __XXXXXX,__X____X,________,
  __X___XX,__X____X,X_______,
  __X___XX,__X_____,X_____X_,
  __X___XX,__X_____,XX____X_,
  __X___XX,__X___X_,_X____X_,
  __XXXXXX,__X_XX__,_XX__X__,
  __X___X_,__XXX___,__XX_X__,
  ________,__XX____,___XXX__,
  ________,________,_____XX_,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_7761[ 72] = { /* code 7761 */
  ________,________,________,
  ________,________,________,
  ________,________,__XX____,
  ________,_______X,XXXX____,
  __XXXXXX,_XXXXXXX,________,
  __X___X_,______XX,________,
  __X___X_,______XX,________,
  __X___X_,______XX,____XX__,
  __X___X_,_XXXXXXX,XXXX____,
  __XXXXX_,___X__XX,__X_____,
  __X___X_,___X__XX,__X_____,
  __X___X_,___X__XX,__X__X__,
  __X___XX,XXXXXXXX,XXXXXXX_,
  __X___X_,___X__XX,__X_____,
  __XXXXX_,___X__XX,__X_____,
  __X___X_,___X__XX,__X_____,
  __X___X_,___X__XX,__X_X___,
  __X___X_,XXXXXXXX,XXXXXX__,
  __X___X_,______XX,________,
  __XXXXX_,______XX,________,
  __X___X_,______XX,____X___,
  ________,_XXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_786E[ 72] = { /* code 786E */
  ________,________,________,
  ________,________,________,
  ________,_____XXX,________,
  ________,_____X__,__X_____,
  _XXXXXXX,XX__XXXX,XXXX____,
  _____X__,____X___,_XX_____,
  _____X__,___X____,_X______,
  ____XX__,___X____,X_______,
  ____X___,__XXXXXX,XXXXXX__,
  ____X___,_X_XX___,X___X___,
  ___XX___,X__XX___,X___X___,
  ___XXXXX,X__XX___,X___X___,
  ___XX___,X__XXXXX,XXXXX___,
  __X_X___,X__XX___,X___X___,
  _X__X___,X__XX___,X___X___,
  ____X___,X__XX___,X___X___,
  ____X___,X__XXXXX,XXXXX___,
  ____X___,X__X____,X___X___,
  ____XXXX,X__X____,X___X___,
  ____X___,__XX____,X___X___,
  ___XX___,__X_____,X___X___,
  ________,_X______,XXXXX___,
  ________,X_______,____X___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_793A[ 72] = { /* code 793A */
  ________,________,________,
  ________,________,________,
  ________,________,__X_____,
  ____XXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,____XX__,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,___XX___,________,
  _______X,___XX___,________,
  ______XX,X__XX___,X_______,
  ______XX,___XX___,_X______,
  _____XX_,___XX___,_XX_____,
  _____X__,___XX___,__XX____,
  ____X___,___XX___,___XX___,
  ___X____,___XX___,____XX__,
  __X_____,___XX___,____X___,
  _X_____X,___XX___,________,
  ________,XXXXX___,________,
  ________,__XX____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_8BA4[ 72] = { /* code 8BA4 */
  ________,________,________,
  ________,________,________,
  ____X___,______X_,________,
  _____X__,______XX,________,
  _____XX_,______X_,________,
  ______X_,______X_,________,
  ______X_,______X_,________,
  ________,______XX,________,
  ________,______XX,________,
  _____X__,______XX,________,
  _XXXXXX_,______XX,________,
  _____X__,_____XXX,________,
  _____X__,_____XXX,________,
  _____X__,_____X__,X_______,
  _____X__,_____X__,X_______,
  _____X__,_X__XX__,X_______,
  _____X__,_X__X___,_X______,
  _____X_X,X__XX___,_X______,
  _____XXX,___X____,__X_____,
  _____XX_,__X_____,__XX____,
  _____X__,_X______,___XX___,
  ________,X_______,____XXX_,
  ______XX,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_ST_24_8BC4[ 72] = { /* code 8BC4 */
  ________,________,________,
  ________,________,________,
  ________,________,____X___,
  ___X____,________,___XXX__,
  ____X___,__XXXXXX,XXX_____,
  ____XX__,_______X,________,
  _____X__,_X_____X,____X___,
  ________,__X____X,___XX___,
  ________,___X___X,___X____,
  _____X__,___XX__X,__X_____,
  _XXXXXX_,____X__X,_X______,
  _____X__,____X__X,_X______,
  _____X__,_______X,____XX__,
  _____X__,XXXXXXXX,XXXX____,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,__X____X,________,
  _____X__,_X_____X,________,
  _____X__,X______X,________,
  _____X_X,_______X,________,
  _____XX_,_______X,________,
  _____X__,_______X,________,
  ________,_______X,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFont_ST_24_CharInfo[11] = {
   {  12,  12,  2, acGUI_FontFont_ST_24_0020 } /* code 0020 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_5206 } /* code 5206 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_544A } /* code 544A */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_62A5 } /* code 62A5 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_63D0 } /* code 63D0 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_7720 } /* code 7720 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_7761 } /* code 7761 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_786E } /* code 786E */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_793A } /* code 793A */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_8BA4 } /* code 8BA4 */
  ,{  24,  24,  3, acGUI_FontFont_ST_24_8BC4 } /* code 8BC4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop11 = {
   0x8BC4 /* first character */
  ,0x8BC4 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[ 10] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop10 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  9] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop9 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  8] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop8 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  7] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop7 = {
   0x7761 /* first character */
  ,0x7761 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  6] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop6 = {
   0x7720 /* first character */
  ,0x7720 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  5] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop5 = {
   0x63D0 /* first character */
  ,0x63D0 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  4] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop4 = {
   0x62A5 /* first character */
  ,0x62A5 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop3 = {
   0x544A /* first character */
  ,0x544A /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  2] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop2 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_ST_24_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontFont_ST_24_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_ST_24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_ST_24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_ST_24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

