/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font_HNLP_18.c                                        *
* Font:        HelveticaNeueLT Pro 43 LtEx                           *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Edit/Insert/Left      at character 0x2F (47)                       *
* Edit/Insert/Right     at character 0x2F (47)                       *
* Edit/Insert/Left      at character 0x2F (47)                       *
* Edit/Insert/Right     at character 0x2F (47)                       *
* Edit/Shift/Up         at character 0x2B (43)                       *
* Edit/Insert/Right     at character 0x2B (43)                       *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont_HNLP_18;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_002B[ 36] = { /* code 002B, PLUS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  _XXXXXXX,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_002D[ 36] = { /* code 002D, HYPHEN-MINUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_002F[ 36] = { /* code 002F, SOLIDUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ___X____,________,
  ___X____,________,
  __X_____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0030[ 36] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  __XX___X,X_______,
  __X_____,X_______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  _X______,_X______,
  __X_____,X_______,
  __XX___X,X_______,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0031[ 36] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  __XXXX__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0032[ 36] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,X_______,
  ________,X_______,
  _______X,________,
  _____XX_,________,
  ___XX___,________,
  __X_____,________,
  _X______,________,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0033[ 36] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,X_______,
  _______X,________,
  ____XXX_,________,
  _______X,________,
  ________,X_______,
  _X______,X_______,
  __X____X,X_______,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0034[ 36] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _____XX_,________,
  ____X_X_,________,
  ___X__X_,________,
  __X___X_,________,
  __X___X_,________,
  _X____X_,________,
  XXXXXXXX,X_______,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0035[ 36] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  __X_____,________,
  __X_____,________,
  _X______,________,
  _X_XXXX_,________,
  _XX____X,________,
  ________,X_______,
  ________,X_______,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0036[ 36] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X____X,________,
  __X_____,X_______,
  _X______,________,
  _X_XXXX_,________,
  _XX____X,________,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0037[ 36] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  ________,X_______,
  _______X,________,
  ______X_,________,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  ____X___,________,
  ____X___,________,
  ____X___,________,
  ___XX___,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0038[ 36] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,X_______,
  __X____X,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_0039[ 36] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __X____X,________,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  __X___XX,X_______,
  ___XXX__,X_______,
  _X_____X,________,
  __X____X,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont_HNLP_18_003A[ 36] = { /* code 003A, COLON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _____X__,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFont_HNLP_18_CharInfo[14] = {
   {  10,  10,  2, acGUI_FontFont_HNLP_18_002B } /* code 002B */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_002D } /* code 002D */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_002F } /* code 002F */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0030 } /* code 0030 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0031 } /* code 0031 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0032 } /* code 0032 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0033 } /* code 0033 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0034 } /* code 0034 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0035 } /* code 0035 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0036 } /* code 0036 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0037 } /* code 0037 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0038 } /* code 0038 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_0039 } /* code 0039 */
  ,{  10,  10,  2, acGUI_FontFont_HNLP_18_003A } /* code 003A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_HNLP_18_Prop3 = {
   0x002F /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontFont_HNLP_18_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_HNLP_18_Prop2 = {
   0x002D /* first character */
  ,0x002D /* last character  */
  ,&GUI_FontFont_HNLP_18_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont_HNLP_18_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFont_HNLP_18_Prop1 = {
   0x002B /* first character */
  ,0x002B /* last character  */
  ,&GUI_FontFont_HNLP_18_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont_HNLP_18_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont_HNLP_18 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont_HNLP_18_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

