/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: XslZk.c                                               *
* Font:        ËÎÌו                                                  *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\XslZk.txt        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontXslZk;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontXslZk_4EAE[ 63] = { /* code 4EAE */
  ________,________,________,
  ________,_XX_____,________,
  ________,__X_____,________,
  ________,__X_____,_XX_____,
  __XXXXXX,XX_XXXXX,X_______,
  _____X__,______XX,________,
  _____XXX,XXXXXXX_,________,
  _____XX_,______X_,________,
  _____XXX,XXXXXXX_,________,
  _____X__,______X_,________,
  ________,________,__X_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  _XX_____,________,_X______,
  _______X,XXXXXX__,________,
  _______X,____XX__,________,
  ______XX,____XX__,________,
  ______X_,____XX__,__X_____,
  ______X_,____XX__,__X_____,
  _____X__,_____XXX,XXXX____,
  __XXX___,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontXslZk_5B57[ 63] = { /* code 5B57 */
  ________,________,________,
  ________,_X______,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___X____,________,_X______,
  __XX____,________,X_______,
  _____XXX,XXXXXXXX,________,
  ________,_____XX_,________,
  ________,____X___,________,
  ________,__XX____,________,
  ________,__X_____,__X_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  _______X,XXX_____,________,
  ________,_XX_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontXslZk_5E93[ 63] = { /* code 5E93 */
  ________,________,________,
  ________,__X_____,________,
  ________,___X____,________,
  ___X____,___X____,_XX_____,
  ___XXXXX,XXX_XXXX,X_______,
  ___XX___,__X_____,________,
  ___XX___,_X______,_X______,
  ___X_XXX,XXXXXXXX,XXX_____,
  ___X____,_X______,________,
  ___X____,X___XX__,________,
  ___X____,X___X___,________,
  ___X___X,____X__X,X_______,
  ___X___X,XXXXXXX_,________,
  ___X____,____X___,________,
  ___X____,____X___,_XX_____,
  ___X_XXX,XXXXXXXX,XXXX____,
  __X_____,____X___,________,
  __X_____,____X___,________,
  _X______,____X___,________,
  _X______,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontXslZk_5F90[ 63] = { /* code 5F90 */
  ________,________,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ____X___,___X_X__,________,
  ___XX___,__XX__X_,________,
  ___X____,__X____X,________,
  __X__XX_,_X______,XX______,
  _X___X__,X______X,_XXX____,
  ____X__X,_XXXXXXX,X_X_____,
  ____X_X_,____X___,________,
  ___XX___,____X___,________,
  __X_X___,____X___,_XX_____,
  _X__X___,XXXXXXXX,X_______,
  ____X___,_X__X___,________,
  ____X___,_XX_X__X,________,
  ____X___,XX__X___,X_______,
  ____X___,X___X___,_XX_____,
  ____X__X,____X___,__X_____,
  ____X_X_,__XXX___,__X_____,
  ____X___,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontXslZk_677E[ 63] = { /* code 677E */
  ________,________,________,
  ____XX__,______X_,________,
  ____X___,______X_,________,
  ____X___,___X__X_,________,
  ____X___,___X__X_,________,
  ____X__X,___X___X,________,
  __XXXXX_,__X____X,________,
  ____X___,__X_____,X_______,
  ____XX__,_X______,XX______,
  ___XX_X_,_X______,_XX_____,
  ___XX__X,X___XX__,________,
  ___XX__X,____X___,________,
  __X_X___,____X___,________,
  __X_X___,___X____,________,
  _X__X___,___X___X,________,
  ____X___,__X____X,________,
  ____X___,__X_____,X_______,
  ____X___,_X______,XX______,
  ____X___,_XXXXXXX,_X______,
  ____X___,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontXslZk_CharInfo[5] = {
   {  21,  21,  3, acGUI_FontXslZk_4EAE } /* code 4EAE */
  ,{  21,  21,  3, acGUI_FontXslZk_5B57 } /* code 5B57 */
  ,{  21,  21,  3, acGUI_FontXslZk_5E93 } /* code 5E93 */
  ,{  21,  21,  3, acGUI_FontXslZk_5F90 } /* code 5F90 */
  ,{  21,  21,  3, acGUI_FontXslZk_677E } /* code 677E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontXslZk_Prop5 = {
   0x677E /* first character */
  ,0x677E /* last character  */
  ,&GUI_FontXslZk_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontXslZk_Prop4 = {
   0x5F90 /* first character */
  ,0x5F90 /* last character  */
  ,&GUI_FontXslZk_CharInfo[  3] /* address of first character */
  ,&GUI_FontXslZk_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontXslZk_Prop3 = {
   0x5E93 /* first character */
  ,0x5E93 /* last character  */
  ,&GUI_FontXslZk_CharInfo[  2] /* address of first character */
  ,&GUI_FontXslZk_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontXslZk_Prop2 = {
   0x5B57 /* first character */
  ,0x5B57 /* last character  */
  ,&GUI_FontXslZk_CharInfo[  1] /* address of first character */
  ,&GUI_FontXslZk_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontXslZk_Prop1 = {
   0x4EAE /* first character */
  ,0x4EAE /* last character  */
  ,&GUI_FontXslZk_CharInfo[  0] /* address of first character */
  ,&GUI_FontXslZk_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontXslZk = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,21 /* height of font  */
  ,21 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontXslZk_Prop1}
  ,18 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

